### ISSUE TITLE
Model extension should be anonymous

### ISSUE THREAD

**Issue by koskimas** [seegno/objection-guid#15]
Hi!

First of all, thank you for building this plugin for objection. Having a collection of good quality plugins such as this one for the most common problems will do a lot of good for the objection ecosystem.

Objection changed its best practices regarding the name of the extending class returned from the mixin function. The class should not have a name. The reason for this change is explained in [this](https://github.com/Vincit/objection.js/issues/475) issue.

Please consider updating your plugin to follow the updated practices.

**Comment by joaonice** [comment]
@koskimas, done 😉
